name: admin_panel_study_hub
description: "MT"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  email_validator: ^3.0.0
  
  #* Riverpod
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  #* Router
  auto_route: ^10.0.1

  #* Firebase (BaaS)
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5

  #* Hive (Local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #! .env
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  #* Route_gen
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  assets:
    - .env
    - lib/logic/assets/Images/eye.gif

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700